[mongodb]
mongodb.kimidi.site

[catalogue]
catalogue.kimidi.site

[frontend]
frontend.kimidi.site

[mysql]
mysql.kimidi.site

[shipping]
shipping.kimidi.site
[rabbitmq]
rabbitmq.kimidi.site

[all:vars]
ansible_user=ec2-ansible_user
ansible_password=DevOps321
